<?php
require_once __DIR__ . '/includes/session.php';
requireLogin();

require_once __DIR__ . '/vendor/PHPGangsta/GoogleAuthenticator.php';

$user    = db()->fetchOne("SELECT * FROM users WHERE id=?", [$_SESSION['user_id']]);
$ga      = new PHPGangsta_GoogleAuthenticator();
$success = '';
$error   = '';

// ── ENABLE FLOW ──────────────────────────────────────────────────────────────
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $action = $_POST['action'] ?? '';

    // Step 1: Generate a new secret and store it in session (not DB yet)
    if ($action === '2fa_generate') {
        $_SESSION['2fa_setup_secret'] = $ga->createSecret();
        redirect(SITE_URL . '/2fa-setup.php');
    }

    // Step 2: User submits the code to confirm and activate
    if ($action === '2fa_enable') {
        $secret = $_SESSION['2fa_setup_secret'] ?? '';
        $code   = trim($_POST['totp_code'] ?? '');

        if (!$secret) {
            $error = 'Session expired. Please start again.';
        } elseif (!$ga->verifyCode($secret, $code, 1)) {
            $error = 'Invalid code. Make sure you scanned the QR code and entered the correct 6-digit number.';
        } else {
            db()->execute(
                "UPDATE users SET totp_secret=?, two_factor_enabled=1 WHERE id=?",
                [$secret, $_SESSION['user_id']]
            );
            unset($_SESSION['2fa_setup_secret']);
            logActivity($_SESSION['user_id'], '2FA_ENABLED', 'User enabled two-factor authentication');
            $success = 'Two-factor authentication has been enabled!';
            $user = db()->fetchOne("SELECT * FROM users WHERE id=?", [$_SESSION['user_id']]);
        }
    }

    // Disable 2FA — require current password as confirmation
    if ($action === '2fa_disable') {
        $password = $_POST['confirm_password'] ?? '';
        if (!verifyPassword($password, $user['password'])) {
            $error = 'Incorrect password. 2FA was not disabled.';
        } else {
            db()->execute(
                "UPDATE users SET totp_secret=NULL, two_factor_enabled=0 WHERE id=?",
                [$_SESSION['user_id']]
            );
            unset($_SESSION['2fa_setup_secret']);
            logActivity($_SESSION['user_id'], '2FA_DISABLED', 'User disabled two-factor authentication');
            $success = 'Two-factor authentication has been disabled.';
            $user = db()->fetchOne("SELECT * FROM users WHERE id=?", [$_SESSION['user_id']]);
        }
    }
}

// QR code generation
$setupSecret  = $_SESSION['2fa_setup_secret'] ?? null;
$qrUrl        = '';
if ($setupSecret) {
    $label   = urlencode($user['email']);
    $issuer  = urlencode('ClinicCare');
    $qrUrl   = $ga->getQRCodeGoogleUrl("ClinicCare:{$user['email']}", $setupSecret, 'ClinicCare', ['width' => 250, 'height' => 250]);
}

$pageTitle = '2FA Setup';
$activeNav = 'profile';
include __DIR__ . '/includes/header.php';
?>

<div class="page-header">
    <h1>🔐 Two-Factor Authentication</h1>
    <p>Add an extra layer of security to your account using Google Authenticator</p>
</div>

<?php if ($success): ?>
<div class="alert alert-success" data-auto-dismiss="5000">✅ <?= htmlspecialchars($success) ?></div>
<?php endif; ?>
<?php if ($error): ?>
<div class="alert alert-danger">⚠️ <?= htmlspecialchars($error) ?></div>
<?php endif; ?>

<div style="max-width:680px;margin:0 auto;">

<?php if ($user['two_factor_enabled']): ?>
<!-- ── 2FA IS ON ─────────────────────────────────────────────────────────── -->
<div class="card">
    <div class="card-header">
        <span class="card-title">🛡️ 2FA Status</span>
        <span class="badge badge-success" style="margin-left:auto;">Enabled</span>
    </div>
    <div class="card-body">
        <p style="color:var(--text-secondary);margin-bottom:20px;">
            Your account is protected with Google Authenticator. Every login will require
            a 6-digit code from your authenticator app.
        </p>
        <div style="background:var(--surface-2);border:1px solid var(--border);border-radius:10px;padding:16px;margin-bottom:20px;">
            <div style="font-weight:600;margin-bottom:8px;">✅ Active on this account</div>
            <div style="font-size:13px;color:var(--text-muted);">
                Codes are generated by the Google Authenticator app on your phone.
            </div>
        </div>

        <hr style="border:none;border-top:1px solid var(--border);margin:20px 0;">
        <div style="background:#fff3cd;border:1px solid #ffc107;border-radius:8px;padding:14px;margin-bottom:16px;">
            <strong>⚠️ Danger Zone</strong><br>
            <span style="font-size:13px;">Disabling 2FA will remove the extra security from your account.</span>
        </div>

        <form method="POST">
            <input type="hidden" name="action" value="2fa_disable">
            <div class="form-group">
                <label class="form-label">Confirm your password to disable 2FA</label>
                <input type="password" name="confirm_password" class="form-control" required placeholder="Enter your current password">
            </div>
            <button type="submit" class="btn btn-danger"
                    onclick="return confirm('Are you sure you want to disable two-factor authentication?')">
                🔓 Disable Two-Factor Authentication
            </button>
        </form>
    </div>
</div>

<?php elseif ($setupSecret): ?>
<!-- ── SETUP IN PROGRESS ──────────────────────────────────────────────────── -->
<div class="card">
    <div class="card-header"><span class="card-title">📱 Scan QR Code</span></div>
    <div class="card-body">
        <div style="display:flex;flex-direction:column;align-items:center;gap:20px;">

            <p style="color:var(--text-secondary);text-align:center;">
                Open <strong>Google Authenticator</strong> on your phone, tap the <strong>+</strong> button,
                then scan the QR code below.
            </p>

            <div style="background:#fff;padding:16px;border-radius:12px;border:2px solid var(--primary);box-shadow:0 4px 16px rgba(0,0,0,0.1);">
                <img src="<?= htmlspecialchars($qrUrl) ?>" alt="QR Code" width="220" height="220">
            </div>

            <div style="text-align:center;">
                <div style="font-size:12px;color:var(--text-muted);margin-bottom:4px;">Can't scan? Enter this key manually:</div>
                <code style="background:var(--surface-2);border:1px solid var(--border);padding:8px 16px;border-radius:6px;font-size:16px;letter-spacing:3px;font-weight:700;display:inline-block;">
                    <?= htmlspecialchars($setupSecret) ?>
                </code>
            </div>

            <div style="width:100%;">
                <p style="text-align:center;font-size:14px;color:var(--text-secondary);margin-bottom:16px;">
                    After scanning, enter the 6-digit code shown in Google Authenticator:
                </p>
                <form method="POST">
                    <input type="hidden" name="action" value="2fa_enable">
                    <div class="form-group">
                        <label class="form-label">Verification Code</label>
                        <input type="text" name="totp_code" class="form-control"
                               placeholder="000000" maxlength="6" pattern="\d{6}"
                               inputmode="numeric" autocomplete="one-time-code"
                               autofocus required
                               style="font-size:22px;letter-spacing:8px;text-align:center;">
                    </div>
                    <div style="display:flex;gap:12px;flex-wrap:wrap;">
                        <button type="submit" class="btn btn-primary" style="flex:1;">✅ Verify & Enable 2FA</button>
                        <a href="<?= SITE_URL ?>/2fa-setup.php" class="btn btn-secondary">← Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<?php else: ?>
<!-- ── 2FA IS OFF ─────────────────────────────────────────────────────────── -->
<div class="card">
    <div class="card-header">
        <span class="card-title">🛡️ 2FA Status</span>
        <span class="badge badge-secondary" style="margin-left:auto;">Disabled</span>
    </div>
    <div class="card-body">
        <p style="color:var(--text-secondary);margin-bottom:20px;">
            Two-factor authentication adds a second layer of security. After enabling it,
            every login will require a 6-digit code from the Google Authenticator app on your phone.
        </p>

        <div style="display:grid;gap:12px;margin-bottom:24px;">
            <div style="display:flex;align-items:flex-start;gap:12px;padding:14px;background:var(--surface-2);border-radius:8px;border:1px solid var(--border);">
                <span style="font-size:22px;">📱</span>
                <div>
                    <div style="font-weight:600;margin-bottom:2px;">Step 1 — Install the app</div>
                    <div style="font-size:13px;color:var(--text-muted);">Download <strong>Google Authenticator</strong> from the App Store or Google Play.</div>
                </div>
            </div>
            <div style="display:flex;align-items:flex-start;gap:12px;padding:14px;background:var(--surface-2);border-radius:8px;border:1px solid var(--border);">
                <span style="font-size:22px;">📷</span>
                <div>
                    <div style="font-weight:600;margin-bottom:2px;">Step 2 — Scan the QR code</div>
                    <div style="font-size:13px;color:var(--text-muted);">Click the button below, then scan the QR code shown on screen.</div>
                </div>
            </div>
            <div style="display:flex;align-items:flex-start;gap:12px;padding:14px;background:var(--surface-2);border-radius:8px;border:1px solid var(--border);">
                <span style="font-size:22px;">🔢</span>
                <div>
                    <div style="font-weight:600;margin-bottom:2px;">Step 3 — Enter the code</div>
                    <div style="font-size:13px;color:var(--text-muted);">Type the 6-digit code from the app to confirm and activate 2FA.</div>
                </div>
            </div>
        </div>

        <form method="POST">
            <input type="hidden" name="action" value="2fa_generate">
            <button type="submit" class="btn btn-primary btn-lg">
                🔐 Set Up Google Authenticator
            </button>
        </form>
    </div>
</div>
<?php endif; ?>

<div style="margin-top:16px;text-align:center;">
    <a href="<?= SITE_URL ?>/profile.php" style="color:var(--text-muted);font-size:13px;">← Back to Settings</a>
</div>

</div>

<?php include __DIR__ . '/includes/footer.php'; ?>
